port: /dev/ttyUSB0
baud: 1000000
read_rate: 15
write_rate: 25
joints: {
    arm_joint1_frame1_joint: {id: 1, max_angle: 150, min_angle: -150, max_speed: 90},
    arm_joint2_servo_joint: {id: 2, max_angle: 150, min_angle: -150, max_speed: 90},
    arm_joint3_frame1_joint: {id: 3, max_angle: 150, min_angle: -150, max_speed: 90},
    arm_joint4_frame1_joint: {id: 4, max_angle: 100, min_angle: -100, max_speed: 90},
    gripper_joint: {id: 5, max_angle: 70, min_angle: -25, max_speed: 90}
}
controllers: {
    arm_controller: {type: follow_controller, joints: [arm_joint1_frame1_joint, arm_joint2_servo_joint, arm_joint3_frame1_joint, arm_joint4_frame1_joint], action_name: arm_controller/follow_joint_trajectory, onboard: False },
    gripper_controller: {type: follow_controller, joints: [gripper_joint], action_name: gripper_controller/follow_joint_trajectory, onboard: False }
}
