<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find turtlebot_arm_description)/urdf/arm_4dof_hardware.xacro"/>

  <material name="white">
    <color rgba="0.87 0.90 0.87 1.0"/>
  </material>
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>
  <material name="green">
    <color rgba="0.22 0.32 0.14 1.0"/>
  </material>

  <xacro:macro name="turtlebot_arm" params="parent color gripper_color *origin
                                            joints_vlimit pan_llimit pan_ulimit">
    <link name="arm_base_link" />

    <joint name="arm_base_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="arm_base_link" />
    </joint>

    <!-- shoulder pan joint -->
    <dynamixel_AX12_fixed parent="arm_base_link" name="arm_joint1_servo">
      <origin xyz="0 0 ${AX12_WIDTH/2}" rpy="${M_PI/2} 0 ${M_PI/2}"/>
    </dynamixel_AX12_fixed>
    <bioloid_F2_pan_revolute parent="arm_joint1_servo_link" name="arm_joint1_frame1" color="${color}"
                         vlimit="${joints_vlimit}" llimit="${pan_llimit}" ulimit="${pan_ulimit}">
      <origin xyz="0 ${AX12_WIDTH/2+F2_HEIGHT} 0" rpy="${-M_PI/2} ${M_PI/2} ${M_PI}" />
    </bioloid_F2_pan_revolute>

    <!-- shoulder lift joint -->
    <dynamixel_AX12_revolute parent="arm_joint1_frame1_link" name="arm_joint2_servo"
                             vlimit="${joints_vlimit}" llimit="-1.745" ulimit="1.745">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </dynamixel_AX12_revolute>
    <bioloid_F3_fixed parent="arm_joint2_servo_link" name="arm_joint2_frame1" color="${color}">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${M_PI} 0" />
    </bioloid_F3_fixed>
    <bioloid_F3_fixed parent="arm_joint2_frame1_link" name="arm_joint2_frame2" color="${color}">
      <origin xyz="0 0 0" rpy="0 ${M_PI} 0" />
    </bioloid_F3_fixed>

    <!-- elbow joint -->
    <dynamixel_AX12_fixed parent="arm_joint2_frame2_link" name="arm_joint3_servo">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${M_PI} 0" />
    </dynamixel_AX12_fixed>
    <bioloid_F4_revolute parent="arm_joint3_servo_link" name="arm_joint3_frame1" color="${color}"
                         vlimit="${joints_vlimit}" llimit="-2.617" ulimit="2.617">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </bioloid_F4_revolute>
    <bioloid_F3_fixed parent="arm_joint3_frame1_link" name="arm_joint3_frame2" color="${color}">
      <origin xyz="0 0 ${F4_HEIGHT}" rpy="0 ${M_PI} 0" />
    </bioloid_F3_fixed>

    <!-- wrist joint -->
    <dynamixel_AX12_fixed parent="arm_joint3_frame2_link" name="arm_joint4_servo">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${M_PI} 0"/>
    </dynamixel_AX12_fixed>
    <bioloid_F2_revolute parent="arm_joint4_servo_link" name="arm_joint4_frame1" color="${color}"
                         vlimit="${joints_vlimit}" llimit="-1.745" ulimit="1.745">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </bioloid_F2_revolute>
    <bioloid_F3_fixed parent="arm_joint4_frame1_link" name="arm_joint4_frame2" color="${color}">
      <origin xyz="0 0.008 ${F2_HEIGHT}" rpy="0 ${M_PI} ${-M_PI/2}" />
    </bioloid_F3_fixed>

    <!-- gripper -->
    <dynamixel_AX12_fixed parent="arm_joint4_frame2_link" name="gripper_servo">
      <origin xyz="0.01475 0 ${-AX12_WIDTH/2}" rpy="0 ${M_PI/2} 0"/>
    </dynamixel_AX12_fixed>

    <joint name="gripper_joint" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="30" velocity="0.785" lower="-0.40" upper="1.27" />
      <parent link="gripper_servo_link"/>
      <child link="gripper_active_link" />
    </joint>

    <link name="gripper_active_link">
      <inertial>
        <mass value="0.00001" />
        <origin xyz="0 0 0" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                           iyy="1.0" iyz="0.0"
                                     izz="1.0" />
      </inertial>
      <visual>
        <origin xyz=" 0 0 0 " rpy="${-M_PI/2} 0 0" />
        <geometry>
          <mesh filename="package://turtlebot_arm_description/meshes/gripper_left.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 0.02" rpy="0 0 0" />
        <geometry>
          <box size="0.025 0.048 0.06"/>
        </geometry>
      </collision>
    </link>

    <joint name="gripper_mimic_joint" type="revolute">
      <mimic joint="gripper_joint" multiplier="-1.0" offset="0"/>
      <origin xyz="0 0 -0.04" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="30" velocity="0.785" lower="-0.40" upper="1.27" />
      <parent link="gripper_servo_link"/>
      <child link="gripper_mimic_link"/>
    </joint>

    <link name="gripper_mimic_link">
      <inertial>
        <mass value="0.00001" />
        <origin xyz="0 0 0" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                           iyy="1.0" iyz="0.0"
                                     izz="1.0" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 0" />
        <geometry>
          <mesh filename="package://turtlebot_arm_description/meshes/gripper_right.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 -0.02" rpy="0 0 0" />
        <geometry>
          <box size="0.025 0.048 0.06"/>
        </geometry>
      </collision>
    </link>

  </xacro:macro>
</robot>
