controller_list:
  - name: fake_arm_controller
    joints:
      - arm_joint1_frame1_joint
      - arm_joint2_servo_joint
      - arm_joint3_frame1_joint
      - arm_joint4_frame1_joint
      - gripper_link_joint
  - name: fake_gripper_controller
    joints:
      - gripper_joint
      - gripper_mimic_joint
      - gripper_link_joint
